title:  Mi-Gyeong's Profile
email:  rmfosem613@gmail.com
description:  "현재 재주대학교 컴퓨터공학과에 재학중입니다. 다양한 분야의 응용시스템들을 다루며 경험을 쌓고 있습니다. 최근 backend 분야에 관심을 갖고 학습하고 있습니다."
author:             Mi-Gyeong
baseurl:            "/profile-blog"
url:                "https://rmfosem613.github.io"

# Social Profiles
github_username:    rmfosem613

# Add your google-analytics ID here to activate google analytics

theme: jekyll-theme-clean-blog

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
